### ISSUE TITLE
add a way to automatically cross/skip entire sublists.

### ISSUE THREAD

**Issue by jflores82** [jflores82/simchecklists#17]
Add a motion or way to automatically cross/skip entire sublists inside the checklist.

**Comment by jflores82** [comment]
since many times checklists contains conditional/redundant sublists, adding a way to quickly cross/skip those will be helpful.

**Comment by jflores82** [comment]
First version of this featured added on v1.1.2 (https://github.com/jflores82/simchecklists/commit/52d814becbd408a35096f73d084b8ec145f4f62e) 

- double click / tab a sublist title to automatically cross it and move to the next sublist.

**Comment by Lightdasher360** [comment]
Haven't been able to get this working. Double clicked on PC, double tapped on mobile, tried swiping gestures as well to see if something would work -- no success via either platform, on any of the checklists or any light mode. I didn't think the latter were factors, but figured I would try anyway for the sake of fully testing.

**Comment by jflores82** [comment]
do you have more information about what browser, version and operational system you are using? 
i tested on my pc (windows 10) on opera, chrome and firefox.
and on my android phone on chrome and kiwi, seems to be working on all of them. 

i'll re-open the issue as we investigate, i'll just need a bit more information about your enviroment to try and replicate the error on my end.

**Comment by Lightdasher360** [comment]
Sure! Browser is: Firefox 127.0.1~linuxmint1+faye. OS: is LMDE 6 Faye.
Android devices are running Android 12 + Brave (v1.67.119) for Lenovo Tablet (P11 Plus), and Android 11 + Brave (v1.67.119) for Balmuda smartphone.

I can't help but feel the issue is just user error on my end, but I don't see what I could be doing wrong. I even adjusted the speed of my clicks/taps faster and slower, but nothing worked.

**Comment by Lightdasher360** [comment]
More info to give! Just tried with an old Samsung S9+ (Android 10, running Brave 1.58.131), and it worked completely! Still confirmed that the other devices have no such success. Wish I could be sure what the issue could be with all of my other devices, especially the PC..

**Comment by jflores82** [comment]
progress, then. 
for testing purposes, can you test it on a private/incognito tab on one of the devices that aren't working and report back?

depending on the result, i may have a solution to push.

**Comment by Lightdasher360** [comment]
It works perfectly with incognito tabs! Tested with PC and Balmuda smartphone.

**Comment by jflores82** [comment]
excellent, so i think i know what the problem is, i'll try to push a new version with the fix today.

**Comment by jflores82** [comment]
issue solved on 1.1.3: https://github.com/jflores82/simchecklists/commit/f533cfa2f9e764a1c5204cdef89dbb5b92970771

**Comment by jflores82** [comment]
tested ok, closing issue.
