### ISSUE TITLE
Inconsistency with Dark/Light themes

### ISSUE THREAD

**Issue by Lightdasher360** [jflores82/simchecklists#21]
I noticed that, even when forcing dark theme, light theme would be enabled for C172 & CJ4 checklists. Conversely, when forcing light theme, dark theme would be enabled for C337 checklist and C152 checklists. This has been the experience on tablet. For PC, forcing light theme seems ineffective for CJ4, C337, C172, and C152, but works for the initial 4 aircraft checklists (A320Ns, Baron 58, and Bonanza). The opposite seems true for forcing dark theme.

**Comment by jflores82** [comment]
Its probably related to the save/load of session data in php, i'll look into it.

**Comment by jflores82** [comment]
took a deeper look into this, apparently is related to the caching of the page, not capturing the correct theme variable, will make some more tests, but resetting the header response for the cache seem to fix it, will test and drop the fix on the the next update.

**Comment by jflores82** [comment]
Version v1.1.1 of the app is on the live site, if you can test it and report back, i changed the way the caching of the page works, it should at least, now, be consistent, but it might need a browser cache cleanup, first. 
I'll leave this issue open until we can certify its fixed.

**Comment by Lightdasher360** [comment]
Tested on both PC and mobile, works perfectly now!

**Comment by jflores82** [comment]
Issue closed as fixed on v1.1.1 and confirmed on v1.1.2 (https://github.com/jflores82/simchecklists/commit/52d814becbd408a35096f73d084b8ec145f4f62e)
