### ISSUE TITLE
color coding error on some of the lines inside checklist.

### ISSUE THREAD

**Issue by jflores82** [jflores82/simchecklists#24]
some checklist titles aren't loading the titles using theme_text_green and the credits using theme_text_blue.

**Comment by jflores82** [comment]
need to look into the dynamically generated css classes, most likely.

**Comment by jflores82** [comment]
fixed on 1.1.3: https://github.com/jflores82/simchecklists/commit/f533cfa2f9e764a1c5204cdef89dbb5b92970771

loop error fixed.

**Comment by Lightdasher360** [comment]
https://github.com/jflores82/simchecklists/assets/172877039/1447ca43-1ee1-47ed-a438-36a01d604efa

Should've noticed way sooner, but this still seems to apply to my checklists. I'm guessing the only fix would be to use less wording, huh?

**Comment by jflores82** [comment]
the issue here is that you're leaving a blank line after the credits line. the current version of the code only colors blue the text on the last line of the file, its a simple "remove the blank line" and it works, there's no set limit on how the number of words, its the linebreak that determines it. 

i just tested on both mine and yours list and it just that.

did a local fix to test it: 
![image](https://github.com/jflores82/simchecklists/assets/4225319/4151917c-9819-454d-bc75-fd138f91fc82)

it will be fixed for the next update.

**Comment by Lightdasher360** [comment]
Wow, such an embarrassing user error thing on my end! Thank you!

**Comment by jflores82** [comment]
fixed the checklists file on the new update.
